name: randomworkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm i
    - run: npm run lint:fix
    - run: npm run test
    - run: npm run test:watch
    - run: npm run build
    - run: npm run prisma:migrate
    - run: npm run prisma:generate
    - run: npm run format